config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root 'lists#index'
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie, presence: true
  validates :list, presence: true
  validates_uniqueness_of :movie, scope: :list
  validates :comment, length: { minimum: 6 }, allow_blank: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:create]

  def create
    bookmark = Bookmark.new(bookmark_params)
    bookmark.list = @list
    if bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show"
    end
  end

  def destroy
    bookmark = Bookmark.find(params[:id])
    bookmark.destroy
    redirect_to list_path(bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = @list.bookmarks.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
    @bookmark = Bookmark.new
    @bookmarks = Bookmark.where(list_id: params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
<h1>    Movies' Lists</h1>
<br>
<div class="grid">
<ul>
<% @lists.each do |list| %>
<div>
<%= cl_image_tag("The_Movies_Coverart_zwqs9t",
      width: 200, height: 150, crop: :fill) %>
<li><%= link_to list.name, list_path(list) %></li></div>
<% end  %>
</ul>
</div>
<%= link_to "Create a new list", new_list_path, class: "btn btn-primary" %>




</div>

app/views/lists/new.html.erb
<div class="container">
<h1>Create a New List</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class:"create" %>
<% end %>

<%= link_to 'Back', lists_path %>
</div>

app/views/lists/show.html.erb
<div class="container">
<h1>List: <%= @list.name%></h1>

<h3>New Bookmark</h3>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :movie_id, collection: Movie.all, label: 'Select Movie' %>
  <%= f.input :comment, label: 'Comment' %>

  <%= f.button :submit, class: "new-button" %>
<% end %>
<br>
<h3>Bookmarks</h3>
<ul>
<% @bookmarks.each do |bookmark| %>
<li><%= bookmark.comment %>
  <%= link_to "Delete", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</li>
<% end %>
</ul>
<br>


<%= link_to 'Go Back to Lists', lists_path %>
</div>